name: stopwatch
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
playbox:
  name: StopWatch
  description: 
  icon: add_alarm
  background: brown
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "0.16.3"
  flutter_web_plugins: "0.16.3"
  mpcore: "0.16.3"
  mp_build_tools: "0.16.3"
dependency_overrides:
  flutter: "0.16.3"
  # mpcore: "0.16.3"
  mpcore:
    path: /Users/saiakirahui/Documents/mpflutter/mpflutter/packages/mpcore
  flutter_web_plugins: "0.16.3"
